name: Build minfo

on: 
  push:
    branches: [ master ]

jobs:

  build-ubuntu:

    runs-on: ${{matrix.os}}
    strategy:
      matrix: 
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Set up Conda
        if: "!contains(env.COMMIT_MESSAGE, 'skip ci')"
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test
          # environment-file: environment.yml
          python-version: 3.7
          auto-activate-base: false

      - name: Install dependencies
        shell: bash -l {0}
        if: "!contains(env.COMMIT_MESSAGE, 'skip ci')"
        run: |
          conda install --file requirements.txt
      
      - name: Build minfo
        if: "!contains(env.COMMIT_MESSAGE, 'skip ci')" 
        shell: bash -l {0}
        run: pip install -e .

      - name: Run example
        if: "!contains(env.COMMIT_MESSAGE, 'skip ci')" 
        shell: bash -l {0}
        run: |
          cd example
          python example.py

