name: Build minfo

on: 
  push:
    branches: [ master ]

jobs:

  build-ubuntu:

    runs-on: ${{matrix.os}}
    strategy:
      matrix: 
        os: [ubuntu-latest, windows-latest]
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Set up Python
        if: "!contains(env.COMMIT_MESSAGE, 'skip ci')"
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      
      - name: Install dependencies
        if: "!contains(env.COMMIT_MESSAGE, 'skip ci')"
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt
      
      - name: Build minfo
        if: "!contains(env.COMMIT_MESSAGE, 'skip ci')" 
        run: pip install -e .

  build-macos:

    runs-on: macOS-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Set up Python
        if: "!contains(env.COMMIT_MESSAGE, 'skip ci')"
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      
      - name: macOS dependencies
        if: "!contains(env.COMMIT_MESSAGE, 'skip ci')"
        run: brew install llvm libomp
      
      - name: Install dependencies
        if: "!contains(env.COMMIT_MESSAGE, 'skip ci')"
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt
      
      - name: Build minfo
        if: "!contains(env.COMMIT_MESSAGE, 'skip ci')" 
        run: pip install -e .